spring.datasource.url=jdbc:postgresql://localhost:5432/gym_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

logging.pattern.console=[%X{transactionId}] %d{HH:mm:ss} %-5level %logger - %msg%n

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234