spring.application.name=gym-app
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

logging.pattern.console=[%X{transactionId}] %d{HH:mm:ss} %-5level %logger - %msg%n

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.workloadService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.workloadService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.workloadService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.workloadService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.workloadService.waitDurationInOpenState=10s

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.jms.pub-sub-domain=false